### ISSUE TITLE
使单一插件能支持多个视频源

### ISSUE THREAD

**Issue by karma-sun** [muedsa/TvBox#34]
使单一插件能支持多个视频源，且提供UI让用户可以在这些源之间选择切换
现在是否有相应支持？

**Comment by muedsa** [comment]
TvBox的插件本身就是用来提供不同数据源的，如果对某个视频有多个数据源可以在`MediaDetail.playSourceList`中添加。如果想构建一个简单的可操作的UI界面可以参考: https://github.com/muedsa/bilibili-plugin 。

**Comment by muedsa** [comment]
插件本身只提供数据，不支持操作TvBox。

**Comment by muedsa** [comment]
可以不作为Android工程，但是作为app安装可以方便调试。
